builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
     - -s -w
  goos:
    - linux
    - darwin
    - windows
    - freebsd
    - openbsd
    - dragonfly
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: joemiller
    name: homebrew-taps
  commit_author:
    name: goreleaser
    email: goreleaser@joemiller.me
  folder: Formula
  homepage: "https://github.com/joemiller/vault-gpg-token-helper"
  description: "A @hashicorp Vault token helper for GPG (+ yubikey)"
  caveats: |
    You need to set a path to the token helper in your ~/.vault file.
    Run the following to create the ~/.vault file:

    echo "token_helper = \"$(brew --prefix joemiller/taps/vault-gpg-token-helper)/bin/vault-gpg-token-helper\"" > ~/.vault

