builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
     - -s -w
  goos:
    - linux
    - darwin
    - windows
    - freebsd
    - openbsd
    - dragonfly
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
