version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/app
    steps:
      - checkout
      - run: sudo apt -qy install gpgv2
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make deps
      - run: make test

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/app
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  # notes on 'release' workflow - https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
  # - test job runs for all branches but only tags matching version regex
  # - release job runs for no branches and only tags matching version regex
  release:
    jobs:
      - test:
          filters:
            tags:
              # tag selector is necessary because release job depends on this job
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
